# Generated by Django 4.0.2 on 2022-12-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Fully Paid', 'Fully Paid'), ('Partially Paid', 'Partially Paid'), ('Resell', 'Resell')], default=None, max_length=200, null=True, verbose_name='status'),
        ),
    ]
