# Generated by Django 4.0.2 on 2023-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THESISAPP', '0002_alter_lotorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('phase', models.CharField(max_length=30, null=True, verbose_name='phase')),
                ('block', models.CharField(max_length=30, null=True, verbose_name='block')),
                ('lotno', models.CharField(max_length=30, null=True, verbose_name='lot_no.')),
                ('fullname', models.CharField(max_length=99, null=True, verbose_name='fullname')),
                ('birth', models.DateField(null=True, verbose_name='birth')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True, verbose_name='gender')),
                ('contacts', models.CharField(max_length=11, null=True, verbose_name='contacts')),
                ('address', models.CharField(max_length=99, null=True, verbose_name='address')),
                ('email', models.EmailField(max_length=99, null=True, verbose_name='email')),
                ('status', models.CharField(max_length=99, null=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='BookAppointmentLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=250, null=True, verbose_name='reason')),
                ('fullname', models.CharField(max_length=250, null=True, verbose_name='fullname')),
                ('contacts', models.CharField(max_length=11, null=True, verbose_name='contacts')),
                ('email', models.CharField(max_length=250, null=True, verbose_name='email')),
                ('status', models.CharField(max_length=250, null=True, verbose_name='status')),
                ('date', models.DateField(null=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='BuyersFormLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_type', models.CharField(choices=[('Lawn Lot', 'Lawn Lot'), ('Mausoleum', 'Mausoleum'), ('Niche', 'Niche')], max_length=30, null=True, verbose_name='lot_type')),
                ('phase', models.CharField(max_length=30, null=True, verbose_name='phase')),
                ('block', models.CharField(max_length=30, null=True, verbose_name='block')),
                ('lotno', models.CharField(max_length=30, null=True, verbose_name='lot_no.')),
                ('terms', models.CharField(choices=[('Cash', 'Cash'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('Full Down', 'Full Down'), ('Reservation', 'Reservation')], max_length=30, null=True, verbose_name='termsofpayment')),
                ('fullname', models.CharField(max_length=99, null=True, verbose_name='fullname')),
                ('birth', models.DateField(null=True, verbose_name='birth')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True, verbose_name='gender')),
                ('contacts', models.CharField(max_length=11, null=True, verbose_name='contacts')),
                ('address', models.CharField(max_length=99, null=True, verbose_name='address')),
                ('email', models.EmailField(max_length=99, null=True, verbose_name='email')),
                ('status', models.CharField(max_length=99, null=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryFormLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_type', models.CharField(choices=[('Lawn Lot', 'Lawn Lot'), ('Mausoleum', 'Mausoleum'), ('Niche', 'Niche'), ('Apartment Type', 'Apartment Type')], max_length=30, null=True, verbose_name='lot_type')),
                ('phase', models.CharField(max_length=30, null=True, verbose_name='phase')),
                ('block', models.CharField(max_length=30, null=True, verbose_name='block')),
                ('lotno', models.CharField(max_length=30, null=True, verbose_name='lot_no.')),
                ('terms', models.CharField(choices=[('Cash', 'Cash'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('Full Down', 'Full Down'), ('Reservation', 'Reservation')], max_length=30, null=True, verbose_name='termsofpayment')),
                ('fullname', models.CharField(max_length=99, null=True, verbose_name='fullname')),
                ('birth', models.DateField(null=True, verbose_name='birth')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True, verbose_name='gender')),
                ('contacts', models.CharField(max_length=11, null=True, verbose_name='contacts')),
                ('address', models.CharField(max_length=99, null=True, verbose_name='address')),
                ('email', models.EmailField(max_length=99, null=True, verbose_name='email')),
                ('status', models.CharField(max_length=99, null=True, verbose_name='status')),
            ],
        ),
    ]
